var fruits = ["Mango", "Apple", "Banana", "orange"];
console.log(fruits);
var numbers;
numbers = [10, 20, 30, 40, 50];
console.log(numbers);
var thirdFruit = fruits[2];
console.log(thirdFruit);
numbers[1] = 25;
console.log(numbers);
fruits.push("Grape");
console.log(fruits);
var lastFruit = fruits.pop();
console.log(fruits);
console.log(lastFruit);
var firstFruit = fruits.shift();
console.log(firstFruit);
console.log(fruits);
fruits.unshift("Kiwi");
console.log(fruits);
fruits.splice(1, 2);
console.log(fruits);
fruits.splice(2, 0, "pineapple", "pear");
console.log(fruits);
var citrusFruits = fruits.slice(0, 2);
console.log(citrusFruits);
console.log(fruits);
var lastTwoFruit = fruits.slice(2, 4);
console.log(lastTwoFruit);
